-- ==============================================================================
-- RIS & INVENTORY MANAGEMENT SYSTEM - POSTGRES / SUPABASE SCHEMA
-- ==============================================================================

-- 1. EXTENSIONS
-- Required for UUID generation (if you decide to use UUIDs instead of BIGINT)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. UPDATED_AT TRIGGER FUNCTION
-- This will automatically update the updated_at column on rows whenever they are modified.
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- ==============================================================================
-- TABLES
-- ==============================================================================

-- USERS TABLE
-- Note: In a true Supabase setup, you might link this to `auth.users` via a UUID.
-- We are keeping BIGINT IDs here to match the frontend prototype's ID structure,
-- or you can easily swap `BIGINT GENERATED BY DEFAULT AS IDENTITY` with `UUID DEFAULT uuid_generate_v4()`.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL, -- In production, NEVER store plain text. Use Supabase Auth.
    full_name VARCHAR(150),
    email VARCHAR(150) UNIQUE,
    role VARCHAR(50) DEFAULT 'employee', -- 'superadmin', 'admin', 'admin_administrative', 'employee'
    department VARCHAR(100),
    division VARCHAR(100),
    office VARCHAR(100),
    designation VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    
    -- Profile metadata used for prepopulating RIS
    entity_name VARCHAR(150),
    fund_cluster VARCHAR(100),
    responsibility_center_code VARCHAR(100),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- INVENTORY TABLE
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_no VARCHAR(100) UNIQUE NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    description TEXT,
    unit VARCHAR(50),
    quantity INTEGER DEFAULT 0,
    category VARCHAR(100),
    is_available BOOLEAN DEFAULT TRUE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RIS REQUESTS (PARENTS) TABLE
CREATE TABLE IF NOT EXISTS ris_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ris_no VARCHAR(100) UNIQUE,
    status VARCHAR(50) DEFAULT 'draft', -- 'draft', 'pending', 'approved', 'issued', 'rejected'
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    employee_id VARCHAR(50),
    
    -- Header Data (Snapshot at time of request)
    entity_name VARCHAR(150),
    fund_cluster VARCHAR(100),
    division VARCHAR(100),
    office VARCHAR(100),
    responsibility_center_code VARCHAR(100),
    purpose TEXT,
    
    -- Signatures / Names tracking
    requested_by_name VARCHAR(150),
    requested_by_designation VARCHAR(100),
    approved_by_name VARCHAR(150),
    approved_by_designation VARCHAR(100),
    issued_by_name VARCHAR(150),
    issued_by_designation VARCHAR(100),
    received_by_name VARCHAR(150),
    received_by_designation VARCHAR(100),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RIS ITEMS (CHILDREN) TABLE
-- Normalizes the array of items inside a Requisition Slip
CREATE TABLE IF NOT EXISTS ris_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ris_id BIGINT REFERENCES ris_requests(id) ON DELETE CASCADE,
    inventory_id BIGINT REFERENCES inventory(id) ON DELETE SET NULL,
    
    -- Snapshot data (in case inventory details change later)
    stock_no VARCHAR(100),
    description TEXT,
    unit VARCHAR(50),
    
    quantity_requisition INTEGER DEFAULT 0,
    quantity_issue INTEGER DEFAULT 0,
    stock_available_yes BOOLEAN DEFAULT FALSE,
    stock_available_no BOOLEAN DEFAULT FALSE,
    remarks TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- REPORTS LOG TABLE
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(50), -- 'monthly', 'quarterly', 'semestral', 'yearly', 'inventory'
    period_label VARCHAR(100),
    department VARCHAR(100),
    generated_by VARCHAR(150),
    is_auto BOOLEAN DEFAULT FALSE,
    data JSONB NOT NULL, -- Storing the calculated report snaphot dynamically
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50), -- 'success', 'warning', 'info', 'error'
    message TEXT NOT NULL,
    target_role VARCHAR(50), -- Role that should receive the notification
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, -- Nullable, if restricted to a single user
    is_read BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==============================================================================
-- TRIGGERS
-- ==============================================================================

CREATE TRIGGER update_users_modtime
BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

CREATE TRIGGER update_inventory_modtime
BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

CREATE TRIGGER update_ris_requests_modtime
BEFORE UPDATE ON ris_requests FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

CREATE TRIGGER update_ris_items_modtime
BEFORE UPDATE ON ris_items FOR EACH ROW EXECUTE PROCEDURE update_modified_column();


-- ==============================================================================
-- OPTIONAL: SEED DATA FOR TESTING
-- ==============================================================================
/*
INSERT INTO users (employee_id, password_hash, full_name, role, department, designation) VALUES 
('SUPERADMIN', 'password123', 'Super Administrator', 'superadmin', 'Administration', 'System Admin'),
('ADMIN', 'password123', 'Admin User', 'admin', 'Supply', 'Supply Officer'),
('ADMIN_ADMIN', 'password123', 'Administrative Admin', 'admin_administrative', 'Administrative', 'Administrative Officer');
*/
